functionsDirectory = "C:\\Users\\tomer\\Documents\\PrivateNew180425\\CloudeCode\\HatCRM\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "C:\\Users\\tomer\\Documents\\PrivateNew180425\\CloudeCode\\HatCRM\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install && node node_modules/vite/bin/vite.js build"
functions = "C:\\Users\\tomer\\Documents\\PrivateNew180425\\CloudeCode\\HatCRM\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions.batchdata-enrich]
timeout = 45.0

[functions.analyze-deal]
timeout = 120.0

[functions.generate-report]
timeout = 120.0

[functions.generate-ai-notes]
timeout = 50.0

[functions.generate-core-analysis]
timeout = 30.0

[functions.generate-comps]
timeout = 30.0

[functions.generate-negotiation-plan]
timeout = 25.0

[functions.generate-communications]
timeout = 22.0

[functions.ask-deal-question]
timeout = 20.0

[functions.process-agent-sequences]
schedule = "0 13 * * *"

[functions."*"]
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]